
###
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "nombreUsuario" : "benjamin12",
    "nombre" : "benjamin",
    "password" : "123",
    "correo" : "b12@example.com",
    "telefono" : "12345678",
    "idRol" : 2 ,
    "ci" : "2437842"
}

###
PATCH http://localhost:3000/user/editarUsuario
Content-Type: application/json

{    
    "nombreUsuario" : "beni",
    "nombre" : "beni",
    "password" : "123",
    "correo" : "beni@example.com",
    "telefono" : "12345678",
    "idRol" : 4
}

###
GET http://localhost:3000/user/verUsuarios

###
GET http://localhost:3000/user/verUsuario?id=1

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    // --cuenta admin--
    "nombreUsuario": "admin1",	
    "password": "123"
} 

###
GET http://localhost:3000/auth/verificar

###
GET http://localhost:3000/auth/logout

### 
GET http://localhost:3000/admin/panelAdministrativo

### Crear nuevo rol
POST http://localhost:3000/roles/crear
Content-Type: application/json

{
    "nombre": "p"
}

###
Put http://localhost:3000/roles/editar
Content-Type: application/json

{
    
        "oldRol": "cardiologo2",
        "newRol": "cardiologo_principal"
    
}

### Eliminar rol por ID
delete  http://localhost:3000/roles/eliminar
Content-Type: application/json

{
    "nombre": "p"
}


### roles y permisos
 GET http://localhost:3000/roles/permisos

### permisos de un rol
GET http://localhost:3000/roles/permisos

### crear permiso
POST http://localhost:3000/permisos/crear
Content-Type: application/json

{
  "descripcion": "Nuevo"
}

###
Put http://localhost:3000/permisos/editar
Content-Type: application/json

{
  "idPermiso": 5,
    "newDescripcion": "Nuevo2"
}

###
get http://localhost:3000/permisos/mostrarStock/2
### 
GET http://localhost:3000/menus/todos

### 
GET http://localhost:3000/menus/dia/Lunes

### 
PATCH http://localhost:3000/menus/eliminar/1

### 
PATCH http://localhost:3000/menus/editar/1
Content-Type: application/json

{
     "dia": "Martes",
     "productos": [
        {"id": 2},
        {"id": 3}
     ]
           
  
}

### 
POST http://localhost:3000/menus/crear
Content-Type: application/json

{
     "dia": "Lunes",
     "productos": [
        {"id": 2},
        {"id": 3}
     ]    
  
}

### 
GET http://localhost:3000/inventario/mostrarStock/15
