
###
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "nombreUsuario" : "benjamin12",
    "nombre" : "benjamin",
    "password" : "123",
    "correo" : "b12@example.com",
    "telefono" : "12345678",
    "idRol" : 2 ,
    "ci" : "2437842"
}

###
PATCH http://localhost:3000/user/editarUsuario
Content-Type: application/json

{    
    "nombreUsuario" : "beni",
    "nombre" : "beni",
    "password" : "123",
    "correo" : "beni@example.com",
    "telefono" : "12345678",
    "idRol" : 4
}

###
GET http://localhost:3000/user/verUsuarios

###
GET http://localhost:3000/user/verUsuario?id=1

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    // --cuenta admin--
    "nombreUsuario": "dennisbk",	
    "password": "dennis123"
} 

###
GET http://localhost:3000/auth/verificar

###
GET http://localhost:3000/auth/logout

### 
GET http://localhost:3000/admin/panelAdministrativo

### 
GET http://localhost:3000/menus/todos

### 
GET http://localhost:3000/menus/dia/Lunes

### 
PATCH http://localhost:3000/menus/eliminar/1

### 
PATCH http://localhost:3000/menus/editar/1
Content-Type: application/json

{
     "dia": "Martes",
     "productos": [
        {"id": 2},
        {"id": 3}
     ]
           
  
}

### 
POST http://localhost:3000/menus/crear
Content-Type: application/json

{
     "dia": "Lunes",
     "productos": [
        {"id": 2},
        {"id": 3}
     ]
           
  
}